use std::{env, fs, path::PathBuf};

fn main() {
    tauri_build::build();
    generate_plugins_registry();
}

fn generate_plugins_registry() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing"));
    let plugins_dir = manifest_dir.join("src").join("plugins");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));

    let mut modules = Vec::new();
    if let Ok(entries) = fs::read_dir(&plugins_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let filename = match path.file_name().and_then(|name| name.to_str()) {
                Some(name) => name,
                None => continue,
            };
            if !filename.ends_with("_plugin.rs") {
                continue;
            }
            let stem = match path.file_stem().and_then(|name| name.to_str()) {
                Some(stem) => stem.to_string(),
                None => continue,
            };
            modules.push(stem);
        }
    }

    modules.sort();

    let mut output = String::new();
    output.push_str("// @generated by build.rs. Do not edit.\n");
    for module in &modules {
        let path = plugins_dir.join(format!("{module}.rs"));
        let path_str = path.to_string_lossy();
        output.push_str(&format!(
            "#[path = r#\"{}\"#]\npub mod {};\n",
            path_str, module
        ));
    }
    output.push_str("\n");
    output.push_str("pub fn all_plugins() -> Vec<Box<dyn Plugin>> {\n");
    output.push_str("  vec![\n");
    for module in &modules {
        output.push_str(&format!("    {module}::plugin(),\n"));
    }
    output.push_str("  ]\n");
    output.push_str("}\n");

    fs::write(out_dir.join("plugins.generated.rs"), output)
        .expect("Failed to write plugins.generated.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/plugins");
    for module in modules {
        println!("cargo:rerun-if-changed=src/plugins/{module}.rs");
    }
}
